### ISSUE TITLE
Inlining of CSS does not work with FluidEmail

### ISSUE THREAD

**Issue by dahaupt** [pagemachine/typo3-mail-css-inliner#23]
Using the newly introduced `\TYPO3\CMS\Core\Mail\FluidEmail`, CSS is not inlined as expected. 

As already discussed with @mbrodala this is related to this bug in the core:
https://forge.typo3.org/issues/92881

**Comment by dahaupt** [comment]
I think the CSS would not be inlined, even if the Core issue would be solved, because the HTML is rebuild in a later stage of the sending process.

The constructor of the class `vendor/symfony/mailer/SentMessage.php:33` executes `$message->ensureValidity();` which renders the view.

So we currently only really have the option to overwrite rendering methods of  class `FluidEmail`, e.g. method `renderContent()`.

@mbrodala Feel free to ping me on slack to discuss a possible workaround for a hopefully upcoming next release.

**Comment by mbrodala** [comment]
Work on a possible workaround/fix in TYPO3 has started:

71714: [BUGFIX] Fix rendering of specific format body in FluidEmail | https://review.typo3.org/c/Packages/TYPO3.CMS/+/71714

**Comment by mbrodala** [comment]
@dahaupt I now went a completely different way since the mentioned change does not help at all.

As you have discovered, the HTML part of `FluidEmail` is rendered and set numerous (precisely: 3) times during the course of sending an email.

For this reason I now went for replacing `FluidEmail::html()` and inlining the styles there. This won't prevent the seemingly pointless repeated rendering but will at least yield the same result afterwards.
